targets = [ "//:thread" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-algorithm"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-atomic"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-chrono"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-date_time"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-functional"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-math"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-system"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
version = "1.64.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-winapi"
version = "1.64.0"
